### ISSUE TITLE
[HELP] 프레그먼트에서 화면 전환 오류

### ISSUE THREAD

**Issue by cheld536** [Sinabro-littlebylittle/sinabroClient#30]
## 🙋‍♀️ 요청 사항

설정 페이지에서 화면 전환을 할려고 하면 오류가 발생하여 넘어가지 못하는 오류가 발생하고 있습니다.

설정 화면 -> 알림 설정 화면 ( 오류 발생으로 어플 강제 종료됨)
설정 화면 -> 정책 화면 ( 오류발생으로 어플 강제 종료 )

## 👀 시도 해본것

1. AndroidManifest에 환결설정 등록 
2. Intent로 넘어 가볼려고 했으나 오류 발생 
3. 프래그먼트에서 프래그먼트로 넘어가볼려고 했으나 화면 전환이 안되는 상황 발생..

## ✅ 참고 사항

추가적인 공유가 필요한 사항은 Comment

**Comment by developersung13** [comment]
fragment to activity로 레이아웃 전환 방법을 사용하기로 하여 해당 issue는 closing 합니다
